vich_uploader:
    db_driver: orm

    mappings:
        realisation_image:
            uri_prefix: /images/realisation
            upload_destination: '%kernel.project_dir%/public/images/realisation'
           
            
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
