nelmio_cors:
    paths: 
        '^/api':
            allow_origin: ['*']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
            allow_headers: ['*']
            expose_headers: ['*']
            max_age: 3600
   
        