nelmio_cors:
    paths: 
        '^/api':
            allow_origin: ['*,*']
            allow_headers: ['X-Requested-With,X-Requested-With']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE','OPTIONS']
            max_age: 3600
   
        