nelmio_cors:
    paths: 
        'https://127.0.0.1:8000/api':
            allow_origin: ['*,*']
            allow_headers: ['X-Requested-With']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE','OPTIONS']
            max_age: 3600
   
        