nelmio_cors:
    paths: 
        ['*']:
            allow_origin: ['*']
            allow_headers: ['X-Requested-With']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE','OPTIONS']
            max_age: 3600
   
        