nelmio_cors:
    paths: 
        '^/api':
            origin_regex: true
            allow_origin: ['^https?://localhost:?[0-9]+']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
            allow_headers: ['Accept','Content-Type', 'Authorization', 'X-Custom-Header', 'Upgrade-Insecure-Requests']
            expose_headers: ['Link']
            max_age: 3600
   
        